name: Push WorkFlow

on:
  push:
    branches:
      - main

jobs:
  analysis:
    name: Running Static Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - uses: actions/checkout@v2

      - name: Install
        run: composer install

      - name: Run analysis
        run: ./vendor/bin/phpstan analyse

  pint:
    name: Running Pint
    runs-on: ubuntu-latest
    needs: [analysis]

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - uses: actions/checkout@v2

      - name: Install
        run: composer install

      - name: Run pint
        run: ./vendor/bin/pint

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply pint changes

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [pint]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deployment
        uses: appleboy/ssh-action@master
        env:
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: SERVER_PASSWORD
          script: |
            cd /var/www/ecosend
            git checkout -f
            git pull origin main
            echo "$SERVER_PASSWORD" | sudo -S chgrp -R www-data storage bootstrap/cache
            echo "$SERVER_PASSWORD" | sudo -S chmod -R ug+rwx storage bootstrap/cache
            composer install --optimize-autoloader --no-dev
            php artisan optimize
            php artisan migrate --force
            php artisan queue:restart
